export default {
    GET_CATEGOTY: 'GET_CATEGOTY',
    GET_ALL_TASKS: 'GET_ALL_TASKS',
    ADD_NEW_TASK: 'ADD_NEW_TASK',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
    ADD_NEW_CATEGORY: 'ADD_NEW_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY'
};